display_name: Sororain

packager: sororain
packagerEmail: sororain@proton.me
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - Sororain
  - Clash
  - ClashMeta
  - Proxy

generic_name: Sororain

group: Applications/Internet

startup_notify: true